# Generated by Django 3.1.1 on 2020-09-18 16:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0002_auto_20200918_1133'),
    ]

    operations = [
        migrations.RenameField(
            model_name='todo',
            old_name='title',
            new_name='todo',
        ),
    ]
